.\" dummy line
.TH CHICKEN-UNINSTALL 1 "13 Aug 2008"

.SH NAME

chicken-uninstall \- uninstall extension library

.SH SYNOPSIS

chicken-uninstall [OPTION | PATTERN] ...

.SH DESCRIPTION

.I chicken\-uninstall
removes one or more already installed extension libraries for the CHICKEN
Scheme system.
.B PATTERN
may be a regular expression naming multiple extensions or just
an extension name.

.SH OPTIONS

Enter
.B chicken-uninstall\ \-help
for a list of supported command-line options.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_PREFIX
The installation prefix where CHICKEN Scheme and its support files and
libraries are located. Defaults to the installation time prefix given
when configuring the system.

.TP
.B CHICKEN_INSTALL_PREFIX
An alternative installation prefix that will be prepended to extension
installation paths if specified. 

.TP
.B CHICKEN_REPOSITORY
The path where extension libraries are installed. Defaults to the package-library
path selected during configuration (usually
.B $prefix/lib/chicken/<binary\-version>
)


.SH DOCUMENTATION

More information can be found in the
.I CHICKEN\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHORS
The CHICKEN Team

.SH SEE ALSO
.BR chicken-install(1)
.BR chicken-status(1)
.BR chicken(1)
.BR chicken-bug(1)
