.\" dummy line
.TH CHICKEN-INSTALL 1 "13 Aug 2008"

.SH NAME

chicken-install \- download and install extension libraries for Chicken Scheme

.SH SYNOPSIS

chicken-install [OPTION | EXTENSION[:VERSION]] ...

.SH DESCRIPTION

.I chicken\-install
is a program that downloads, compiles and installs a prepackaged
extension library from sources. If no extension name is given on the
command-line, then any existing 
.B setup
scripts in the current
directory will be executed in some unspecified order.

.SH OPTIONS

Enter
.B chicken-install\ \-help
for a list of supported command-line options.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_PREFIX
The installation prefix where CHICKEN Scheme and its support files and
libraries are located. Defaults to the installation time prefix given
when configuring the system.

.TP
.B CHICKEN_INSTALL_PREFIX
An alternative installation prefix that will be prepended to extension
installation paths if specified. 

.TP
.B CHICKEN_REPOSITORY
The path where extension libraries are installed. Defaults to the package-library
path selected during configuration (usually
.B $prefix/lib/chicken/<binary\-version>
)

.SH DOCUMENTATION

More information can be found in the
.I Chicken\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHORS
The CHICKEN Team

.SH SEE ALSO
.BR chicken-uninstall(1)
.BR chicken-status(1)
.BR chicken(1)
.BR csc(1)
.BR chicken-bug(1)
