.\" dummy line
.TH FEATHERS 1 "13 Aug 2008"

.SH NAME

feathers \- a simple source-level debugger for CHICKEN Scheme

.SH SYNOPSIS

feathers [OPTION ...] [PROGRAM ARGUMENTS ...]

.SH DESCRIPTION

.I feathers
runs a program compiled with CHICKEN Scheme and allows basic source-level
debugging like setting breakpoints, single-stepping and inspection of
procedure arguments and global variables.

The Scheme code must be compiled with debug-level 3 for debugging to be
possible. Communication with the debugger takes place by exchanging
messages over a TCP socket, the address and port being given by the
environment variable
.B CHICKEN_DEBUGGER
which holds a connection address of the form
.B <ADDRESS>:<PORT>
.

.SH OPTIONS

.TP
.B \-help
Shows a list of supported command-line options.

.TP
.B \-n
Do not load the default startup file
.B \.feathers

.TP
.B \-port PORT
Select a different TCP port than the default (9999)

.TP
.B \-dir DIRECTORY
Add
.B DIRECTORY
to the list of searched paths for locating source files

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_DEBUGGER
Should hold a TCP server address and port where the debugger is listening.
This variable is set by the debugger when a program is run from it, and
defaults to
.B localhost:9999

.SH DOCUMENTATION

More information can be found in the
.I CHICKEN\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHORS
The CHICKEN Team

.SH SEE ALSO
.BR chicken-uninstall(1)
.BR chicken-status(1)
.BR chicken(1)
.BR csc(1)
.BR chicken-bug(1)
