.\" dummy line
.TH CHICKEN 1 "10 Sep 2002"

.SH NAME

chicken \- A Scheme\-to\-C translator

.SH SYNOPSIS

.B chicken
.I PATHNAME
[
.I OPTION ...
]

.SH DESCRIPTION

.I CHICKEN
is a compiler and interpreter for the programming language
.I Scheme
supporting most of the features as described in the
.I Revised^5 Report on
.I the Algorithmic Language Scheme
\.
The
.B chicken
program is the basic Scheme-to-C translator used in this system.
For a more convenient interface, see the manual page for csc(1).

.SH OPTIONS

Enter
.B chicken\ \-help
for a list of supported command-line options.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_PREFIX
Is used as a prefix directory for support files, include-files and libraries.

.TP
.B CHICKEN_INCLUDE_PATH
Contains one or more pathnames where the compiler should additionally look for
include-files, separated by
.B \;
characters.

.TP
.B CHICKEN_OPTIONS
Holds a string of default compiler options that should apply to every invocation of
.B chicken
\.

.SH DOCUMENTATION

More information can be found in the
.I CHICKEN\ User's\ Manual

.SH AUTHORS

The CHICKEN Team.

.SH SEE ALSO

.BR csc(1)
.BR chicken-bug(1)
