-.\" dummy line
.TH CSI 1 "20 May 2008"

.SH NAME

The
.I CHICKEN
Scheme interpreter

.SH SYNOPSIS

.B csi
[
.I pathname
|
.I option ...
]

.SH DESCRIPTION

.I csi
is an interpreter for the programming language
.I Scheme
supporting most of the features as described in the
.I Revised^5 Report on
.I the Algorithmic Language Scheme
\.
.I csi
is implemented as a program compiled with the
.B chicken
compiler.

.SH OPTIONS

Enter
.B csi \-help
for a list of supported command-line options.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_INCLUDE_PATH
Contains one or more pathnames where the interpreter should also look for include-files, separated by 
.B \;
characters.

.TP
.B CHICKEN_PREFIX
Is used as a prefix directory for support files, include-files and libraries.

.TP
.B CSI_OPTIONS
When set to a string of command-line options, then the options are passed implicitly
to every direct or indirect invocation of
.I csi
.br
Note that runtime options of the form
.B \-\:\.\.\.
can not be passed using this method.

.SH DOCUMENTATION

More information can be found in the
.I CHICKEN\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHOR
The CHICKEN Team

.SH SEE ALSO
.BR chicken(1)
.BR chicken-bug(1)
