#

# message("CMAKE_SYSTEM_PROCESSOR: " ${CMAKE_SYSTEM_PROCESSOR})
if((CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64") OR
    (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86"))
    enable_language(ASM)
    if(CMAKE_ASM_COMPILER_WORKS)
        set(C_HACKED_APPLY 1)
    endif()
endif()

if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(CHICKEN_ARCH x86-64)
else()
    set(CHICKEN_ARCH ${CMAKE_SYSTEM_PROCESSOR})
endif()
